name: 'Include Workflow'
description: 'Include workflow snippets'
inputs:
  workflow-steps:
    required: true
runs:
  using: "composite"
  steps: 
    - run: pwd
      shell: bash
    - run: |
        cat "name: 'Included workflow'" > "$GITHUB_WORKSPACE/included/action.yml"
        cat "runs:" >> "$GITHUB_WORKSPACE/included/action.yml"
        cat "  using: \"composite\"" >> "$GITHUB_WORKSPACE/included/action.yml"
        cat "  steps:" >> "$GITHUB_WORKSPACE/included/action.yml"
      shell: bash
    - run: echo $GITHUB_WORKSPACE
      shell: bash
#     - run: 'cat ${{ inputs.workflow-steps }} >> "$GITHUB_WORKSPACE/included/action.yml"'
#       shell: bash  
#     - run: echo "::set-output name=workflow-uses::$GITHUB_WORKSPACE/included/action.yml"
#       shell: bash  
    # not yet supported :(
    # - uses: $GITHUB_WORKSPACE/included
