name: 'Include Workflow'
description: 'Include workflow snippets'
inputs:
  workflow-steps:
    required: true
    description: 'Workflow steps to run. This is what you would configure for the `steps` property in a normal `job`'
runs:
  using: "composite"
  steps:     
    - run: |
        mkdir "$GITHUB_WORKSPACE/included-workflow"
        echo "name: 'Included workflow'" > "$GITHUB_WORKSPACE/included-workflow/action.yml"
        echo "runs:" >> "$GITHUB_WORKSPACE/inlcuded-workflow/action.yml"
        echo "  using: \"composite\"" >> "$GITHUB_WORKSPACE/included-workflow/action.yml"
        echo "  steps:" >> "$GITHUB_WORKSPACE/included-workflow/action.yml"
      shell: bash    
    - run: 'cat "${{ inputs.workflow-steps }}" >> "$GITHUB_WORKSPACE/included-workflow/action.yml"'
      shell: bash
    - name: Run included workflow
      uses: ./included-workflow
