name: 'Include Workflow'
description: 'Include workflow snippets'
inputs:
  workflow-steps:
    required: true
runs:
  using: "composite"
  steps: 
    - run: echo "FOLDER=included-workflow-$(openssl rand -base64 12)" >> $GITHUB_ENV 
      shell: bash     
    - run: |
        mkdir "$GITHUB_WORKSPACE/$FOLDER"
        echo "name: 'Included workflow'" > "$GITHUB_WORKSPACE/$FOLDER/action.yml"
        echo "runs:" >> "$GITHUB_WORKSPACE/$FOLDER/action.yml"
        echo "  using: \"composite\"" >> "$GITHUB_WORKSPACE/$FOLDER/action.yml"
        echo "  steps:" >> "$GITHUB_WORKSPACE/$FOLDER/action.yml"
      shell: bash    
    - run: 'cat "${{ inputs.workflow-steps }}" >> "$GITHUB_WORKSPACE/$FOLDER/action.yml"'
      shell: bash
    - name: Run included workflow
      uses: ./${{ env.FOLDER }}
      shell: bash
